---
# tasks file for mysql
- name: set Database Server Password
  shell: |
    bash -c "debconf-set-selections <<< 'mysql-server mysql-server/root_password password '"
    bash -c "debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password '"

- name: make sure required packages are installed
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - mysql-server
    - php-mysql
    - python3-mysqldb

